name: Simple Java Build
on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache
        uses: actions/cache@v4.1.2
        with:
            # A list of files, directories, and wildcard patterns to cache and restore
            path: ~/.m2/repository
            # An explicit key for restoring and saving the cache
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-maven-
      - name: Build with maven
        run: mvn clean package
